export const universities = [
    "Houston Community College",
    "Harvard University",
    "Stanford University",
    "Massachusetts Institute of Technology (MIT)",
    "University of California, Berkeley",
    "University of Oxford",
    "University of Cambridge",
    "California Institute of Technology (Caltech)",
    "Princeton University",
    "Yale University",
    "University of Chicago",
    "Columbia University",
    "University of Pennsylvania",
    "Johns Hopkins University",
    "Cornell University",
    "University of Michigan-Ann Arbor",
    "University of Tokyo",
    "ETH Zurich (Swiss Federal Institute of Technology)",
    "National University of Singapore (NUS)",
    "Tsinghua University",
    "University of Texas at Austin",
];

export const majors = [
    "Computer Science",
    "Business Administration",
    "Psychology",
    "Biology",
    "Nursing",
    "Engineering (General)",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Civil Engineering",
    "Economics",
    "Political Science",
    "English Language and Literature",
    "History",
    "Art and Design",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Sociology",
    "Communications",
    "Education",
];