export const universityOptions = [
  "Rice University",
  "University of Houston",
  "University of Houston–Downtown",
  "University of Houston–Clear Lake",
  "Texas Southern University",
  "University of St. Thomas",
  "Houston Christian University",
  "Prairie View A&M University",
  "Sam Houston State University",
  "Texas A&M University at Galveston",
  "UTHealth Houston",
  "Baylor College of Medicine",
  "Houston Community College",
  "Lone Star College",
  "San Jacinto College",
  "Lee College",
  "Galveston College",
  "Texas Woman's University (Houston Center)",
  "DeVry University (Houston)",
  "Remington College (Houston)",
];

export const majorOptions = [
  "Computer Science",
  "Software Engineering",
  "Data Science",
  "Information Systems",
  "Business Administration",
  "Finance",
  "Accounting",
  "Marketing",
  "Economics",
  "Biology",
  "Chemistry",
  "Physics",
  "Mathematics",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Nursing",
  "Psychology",
  "Political Science",
  "Communications",
  "English",
  "Sociology",
  "History",
];
